name: CMS on Deno Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "_cms.ts"
      - "deno.json"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nexinox-cms
          entrypoint: _cms.ts